default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: ubuntu
  host: localhost
  port: 5432

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test
