default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  url: <%= Rails.application.credentials.postgres.dev %>

test:
  <<: *default
  url: <%= Rails.application.credentials.postgres.test %>
