default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] || Rails.application.credentials.postgres[:dev] %>

test:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] || Rails.application.credentials.postgres[:test] %>
