default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  url: postgres://postgres:postgres@localhost/dummy_development

test:
  <<: *default
  url: postgres://postgres:postgres@localhost/dummy_test
