default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'postgresql' %>
  pool: 5
  timeout: 5000
  url: <%= ENV['DATABASE_URL'] || Rails.application.credentials.db %>
development:
  <<: *default
test:
  <<: *default
  url: <%= Rails.application.credentials.db_test %>
production:
  <<: *default
