acme:
  service: Disc
  root: <%= Rails.root.join('acme') %>
  
local_test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage_test') %>

local:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>
