local_test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

qiniu_dev:
  service: Qiniu
  host: assets-yigenongfu.one.work
  access_key: <%= Rails.application.credentials.dig(:qiniu, :access_key) %>
  secret_key: <%= Rails.application.credentials.dig(:qiniu, :secret_key) %>
  bucket: yigenongfu
  protocol: http